"""prevent duplicate centre tests

Revision ID: 2a288fd4f294
Revises: da8bd1745995
Create Date: 2026-09-26 01:31:04.864547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a288fd4f294'
down_revision: Union[str, Sequence[str], None] = 'da8bd1745995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_centre_test', 'centre_tests', ['centre_id', 'test_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_centre_test', 'centre_tests', type_='unique')
    # ### end Alembic commands ###
