"""add diagnostic centres and tests

Revision ID: d6e8413cb775
Revises: f5863b14ea1e
Create Date: 2026-09-25 18:18:55.230044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e8413cb775'
down_revision: Union[str, Sequence[str], None] = 'f5863b14ea1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_centres_id'), 'diagnostic_centres', ['id'], unique=False)
    op.create_table('diagnostic_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_diagnostic_tests_id'), 'diagnostic_tests', ['id'], unique=False)
    op.create_table('centre_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centre_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['diagnostic_centres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['diagnostic_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centre_tests_id'), 'centre_tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centre_tests_id'), table_name='centre_tests')
    op.drop_table('centre_tests')
    op.drop_index(op.f('ix_diagnostic_tests_id'), table_name='diagnostic_tests')
    op.drop_table('diagnostic_tests')
    op.drop_index(op.f('ix_diagnostic_centres_id'), table_name='diagnostic_centres')
    op.drop_table('diagnostic_centres')
    # ### end Alembic commands ###
